### ISSUE TITLE
Rejestr Sprintu

### ISSUE THREAD

**Issue by Immolated** [V-2Schneider/Network-Analyzer#1]
@V-2Schneider wstaw do repo ten arkusz z rejestrem projektu może

**Comment by V-2Schneider** [comment]
Zdaje się, że mieliśmy go gdzieś tu go przepisać, już się tym zajmuję

**Comment by V-2Schneider** [comment]
Wszszszszystko jasne, pracuję nad tym

**Comment by V-2Schneider** [comment]
Temat wałkowany setki razy na forum, zamykam 
(Oraz przepisałem już wszystko do issues)
