### ISSUE TITLE
Ujednolicenie elementu zwracanego przez wyszukiwania

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#19]
Wszystkie wyszukiwania maja zwracać listę node'ów

**Comment by Keyiter** [comment]
nie lepiej było liste connectów?

**Comment by V-2Schneider** [comment]
Inaczej BFS się zawali ;__; + wysyłanie connectów wydaje się nadmiarowe, te node'y wystarczą

**Comment by Keyiter** [comment]
po prostu chodzi o to ze z connectów łatwiej dostać liste nodów, a jak zwracasz liste nodów, to tak naprawdę trzeba zrobić kolejną funkcje która odpakowuje wartości odpowiednich połączeń bo każdy node moze mieć kilka połączeń, więc znowu trza by zarzucić mini przeszukiwanie które znajdzie następny node w liście połączeń aktualnego node'a żeby dostać wartość połaczenia

**Comment by V-2Schneider** [comment]
A nie wystarczy tylko w tym miejscu:
```
if(nextNode != _entryNode) {
                if (MakeGreedySearch(nextNode, _exitNode, _mapOfNode)) {
                    sRes.add(_mapOfNode.get(_entryNode).getOutgoing().get(connectionNumber));
                    return true;
                }
}
```
zmienić dodawanie połączeń na dodawanie nodesów?

**Comment by V-2Schneider** [comment]
O, a gdyby w tym miejscu dodać od razu sumowanie kosztu? Wtedy na końcu otrzymamy listę nodesów i koszt, który będzie można wysłać klientowi w, przykładowo, klasie pomocniczej, której polami będzie lista i koszt

**Comment by Keyiter** [comment]
dokładnie tak zrobiłem to na samym początku to kazaliście mi to zmienić...

**Comment by V-2Schneider** [comment]
...oł, no musimy do tego wrócić
W razie co to jeszcze dzisiaj powiem, jaka jest ostateczna decyzja, niech wszyscy jeszcze tutaj usiądą i skomentują, ostro tu jeszcze myślimy xd

**Comment by Immolated** [comment]
@Keyiter to najwyraźniej ja ciebie nie zrozumiałem wcześniej jak to tłumaczyłeś ;___; 

Z założenia serwer w odpowiedzi na zapytanie o ścieżkę _musi_ zwrócić jakoś zarówno ścieżkę jak i jej koszt.
Po przyjrzeniu się metodzie _GreedySeach_ (@Keyiter może zrefaktoryzuj nazwę na _GreedySea**r**ch_) razem z @V-2Schneider, @Taczi  i @Sensei2137 stwierdziliśmy, że najłatwiej będzie obliczać koszt znalezionej ścieżki dodając do siebie wartości wszystkich połączeń od razu w metodzie wyszukującej, czyli:

Jak już przeszukiwanie dojdzie do wyjściowego _Node'a_, to wracając z niego do góry, wartości przechodzonych połączeń powinny być do siebie dodawane "po drodze" (co zresztą idealnie pasuje do tej metody).

Gdyby we wskazanym wcześniej fragmencie kodu (rekurencyjnym wychodzeniu do góry ścieżki) dopisać dodawanie do jakiejś zmiennej (np `int sumValue`?) wartości połączenia łączącego wierzchołek, w którym obecnie "znajduje się" algorytm z następnym wierzchołkiem w znalezionej ścieżce i zapętlić to do końca, to mamy problem z głowy.

Skąd wziąć wartość połączenia bez przeszukiwania za każdym razem list poprzedników i następników? (zakładając, że już wiesz, w którym _Nodzie_  jesteś i do którego _Node'a_ idzie to połaczenie) 
Otóż potrzebna będzie metoda `getConnectionValueById(int idFrom, int idTo)` zwracająca tą wartość.

Ja mógłbym to napisać, tylko nie wiem na jakiej gałęzi xd Ktoś coś ? Chyba, że lepiej żebym się nie mieszał w gałęź od przeszukiwań na razie i @Keyiter albo @Taczi napiszecie.

Trzeba ją napisać i dorzucić do klasy Graph (tam w środku _de facto_ i tak trzeba będzie odszukać konkretne połaczenie w MapOfConnections i wyciągnąć z niego to co potrzebujemy, więc _jakiegoś_ przeszukiwania nie unikniemy, ale przynajmniej nie będzie to przeszukiwanie list poprzedników i następników, no i w kodzie samych metod wyszukujących ścieżkę w grafie nie będzie bałaganu, bo tam dopisze się tylko coś w stylu :
```
sumValue = sumValue + getConnectionValueById(nodeWKtorymJestem.getId(), nodeDoKtoregoIdzieSciezka.getId())
``` 
)

Pozostaje kwestia jak zwracać ten wynik - moja propozycja to stworzenie pomocniczej klasy:

```
public class pathResponse{
   private int sumValue;
   ArrayList<Node> path;

   //do tego gettery, i konstruktor przyjmujący argumenty do obu pól
}
```

Po znalezieniu ścieżki wasze metody wywoływałyby po prostu :
```
pathResponse wynik = new pathResponse(waszSumValue, listaNode'ów)
return wynik
```

Ja do tego napiszę jeszcze dwie metody do klasy Parser, które będą parsować ten obiekt do i z JSONa (`pathResponseToJsonString` i `jsonStringToPathResponse`).

Dajcie jakiś feedback jak to widzicie.

**Comment by Immolated** [comment]
Dodano klasę PathResult i dopisano odpowiednie metody do parsera, a metody przeszukujące zwracają obiekt klasy PathResult.

Zamykam.
