### ISSUE TITLE
Konfiguracja środowiska

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#4]
Proszę wpisywać się tutaj, jeśli skonfigurowało się swoje środowisko! 
Chodzi oczywiście o zostanie kontrybutorem oraz stworzenia konta na trello, a także zainstalowanie IntelliJ

**Comment by Immolated** [comment]
IntelliJ zainstalowane, Master zcheckoutowany, Trello założone.

**Comment by Sensei2137** [comment]
Konfiguracja done

**Comment by Keyiter** [comment]
Wszystko mam

**Comment by V-2Schneider** [comment]
W sumie @Taczi napisała, że ma skonfigurowane wszystko, to mogę z czystym sumieniem zamknąć
