### ISSUE TITLE
Ustalenie struktury JSON

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#5]
Wprawdzie to się dogadamy na konfie, to jednak muszę to tutaj zaznaczyć, no takie są zasady

**Comment by Immolated** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ustalić struktury plików JSON](https://trello.com/c/6DKdo2LS/1-ustali%C4%87-struktury-plik%C3%B3w-json)

**Comment by Immolated** [comment]
Jakby ktoś nadal nie wiedział o co chodzi ze składnią JSONów, to [tu jest opis](https://www.tutorialspoint.com/json/index.htm).

Na razie wymyśliłem coś takiego:

```
//JSON przychodzący (wysyłany przez klienta do naszej aplikacji)
{
    "idZapytaniaCzyCoś": "WYGENEROWANA_WARTOŚĆ",
    "startNode": {
        "id": "WARTOŚĆ ",
        "name": "NAZWA"	
    }
    "exitNode" : {
        "id": "WARTOŚĆ ID",
        "name": "NAZWA"	
    }
}
```

Struktura JSONa do odesłania ( z gotową trasą po naszej sieci) będzie chyba bardziej tricky, bo nie będzie mieć stałej długości, więc na razie nic w tym temacie nie mam. 

Ktoś, coś @Keyiter  @V-2Schneider @Taczi  @Sensei2137  ?

**Comment by V-2Schneider** [comment]
Najprostszym sposobem byłoby wysyłanie trasy odcinek po odcinku, tylko trzeba by wtedy zaznaczyć, który odcinek jest ostatni; warto się jednak zapytać _**Product Ownera**_, czy nie ma problemu, by dodać jakiegoś boola "isLast" czy cóś
Aaalbo Ty zadecydujesz, Panie _"**Proxy Product Owner**_ @Immolated

**Comment by V-2Schneider** [comment]
Nie lepiej by było wysyłać wierzchołki zamiast połączeń?
`
{
    "idZapytaniaCzyCoś": "WYGENEROWANA_WARTOŚĆ",
    "Node": {
        "id": "WARTOŚĆ ",
        "name": "NAZWA",	
        "type": "TYP"
        "outgoing": "JAKAŚ_LISTA"
        "incoming": "JAKAŚ LISTA2"
    }
}`
JSON podobno nie robi problemów i można wysyłać tablice
To by także ułatwiło wysłanie ścieżki, bo można po prostu wysłać:
`
{
    "idWyslaniaTakMysle: "WARTOSC_GENEROWANA",
    "Lista": [
     { 
         "ID": "ID_JAKIEGOŚ_NODESA"
         (...) //inne typenie
     }
    ]
}
`
O, dajmy na to tak, jeśli chodzi o takie rzeczy jak connection to to już program sobie sam zrobi, klient niech się tym nie przejmuje

**Comment by V-2Schneider** [comment]
O Boże czemu nie ma newline'ów oh god oh man

**Comment by Immolated** [comment]
Nie no, odsyłanie każdego odcinka trasy jako osobnego JSONa na pewno będzie bardziej problematyczne, niż cała trasa naraz. 
W sumie na tym podlinkowanym tutorialu dot. JSONów jest info, że można używać notacji `[]` do zapisu tablic, więc może po prostu:
```
{
    "idOdpowiedzi": "WARTOŚĆ",
    "trasa" : [
    { 
        "id": "WARTOŚĆ_ID_1",
        "name": "NAZWA1"
    },
    { 
        "id": "WARTOŚĆ_ID_2",
        "name": "NAZWA2"
    },
    { 
        "id": "WARTOŚĆ_ID_3",
        "name": "NAZWA3"
    },
    
    (...)

    ]
}
```

Parser napiszemy tak, żeby czytał wszystkie elementy do końca tablicy i chyba będzie ok.

**Comment by V-2Schneider** [comment]
Podoba mi się, jeśli do 23:30 nie będzie obiekcji, to zamykam

**Comment by Sensei2137** [comment]
No tak, czyli sumując: input to wierzchołek start oraz meta, output to lista wierzcho... lista obiektów wierzchołek układająca się w ładną trasę, możnaby tam dorzucić jeszcze koszt tej trasy czy co tam będzie u nas

**Comment by V-2Schneider** [comment]
O, jak najbardziej, warto o tym poinformować klienta
No to czekamy do tej 23:30

**Comment by V-2Schneider** [comment]
Dobranoc
