### ISSUE TITLE
Napisanie parsera

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#6]
Chyba dość oczywiste, musimy sobie jednak rozdzielić pracę

**Comment by Immolated** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Napisanie parsera do JSONów](https://trello.com/c/lrF6fDbC/2-napisanie-parsera-do-json%C3%B3w)

**Comment by Immolated** [comment]
Done, w klasie Parser jest 8 statycznych metod : 2 typu utility (readFile i writeToFile) i 6 dedykowanych do serializacji/deserializacji danych (parseGraphToJsonString, parseJsonStringToGraph, parseNodesToJsonString, parseJsonStringToNodes, parsePathToJsonString i parseJsonStringToPath).

Wszystkie zostały przeze mnie przetestowane (starą "dobrą" metodą) i działają, aczkolwiek przydałoby się napisać dla nich porządne testy jednostkowe.
