### ISSUE TITLE
Konfiguracja IntelliJ i przerabianie projektu

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#7]
Nie pamiętam co to było dokładnie pomocy drużyno

**Comment by Immolated** [comment]
Nie wiem, ale skonfigurowałem w końcu IntelliJ, kompiluje mi projekt. Na razie tylko napis "Spring boot" na wyjściu.

**Comment by V-2Schneider** [comment]
W sumie to mamy zrobione 😎
