### ISSUE TITLE
REST dla tego projektu

### ISSUE THREAD

**Issue by V-2Schneider** [V-2Schneider/Network-Analyzer#9]
Dość ważne

**Comment by Immolated** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implementacja przeszukiwania zachłannie](https://trello.com/c/rku5DSpS/6-implementacja-przeszukiwania-zach%C5%82annie)

**Comment by Immolated** [comment]
Aplikacja uruchamia serwer, wywoływanie metod działa, więc zamykam.
Można ewentualnie otworzyć issue z konkretnym opisem co jest do zrobienia w sprawie testów parsowania JSONów, a później samego kontaktu klient - serwer,
